# Day 3 EOD: The Banana Index

Date: 09/02/2026

In [22]:
import pandas as pd

In [23]:
url = 'https://github.com/TheEconomist/banana-index-data/releases/download/1.0/bananaindex.csv'

In [24]:
banana = pd.read_csv(url, index_col = 'entity')

In [25]:
banana = banana.drop(['year', 'Banana values', 'type', 'Chart?', 'Unnamed: 16'], axis='columns')

In [26]:
banana.shape

(160, 11)

In [27]:
banana.head(5)

,emissions_kg,emissions_1000kcal,emissions_100g_protein,emissions_100g_fat,land_use_kg,land_use_1000kcal,Land use per 100 grams of protein,Land use per 100 grams of fat,Bananas index (kg),Bananas index (1000 kcalories),Bananas index (100g protein)
entity,,,,,,,,,,,
Ale,0.488690,0.317338,0.878525,2.424209,0.811485,0.601152,1.577687,3.065766,0.559558,0.362340,0.113771
Almond butter,0.387011,0.067265,0.207599,0.079103,7.683045,1.296870,3.608433,1.495297,0.443134,0.076804,0.026885
Almond milk,0.655888,2.222230,13.595512,4.057470,1.370106,2.675063,12.687839,4.600530,0.751002,2.537364,1.760651
Almonds,0.602368,0.105029,0.328335,0.119361,8.230927,1.423376,4.261040,1.610136,0.689721,0.119923,0.042520
Apple juice,0.458378,0.955184,29.152212,19.754980,0.660629,1.382839,43.232158,26.246743,0.524851,1.090638,3.775280

In [28]:
banana.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160 entries, Ale to Yoghurt
Data columns (total 11 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   emissions_kg                       160 non-null    float64
 1   emissions_1000kcal                 160 non-null    float64
 2   emissions_100g_protein             158 non-null    float64
 3   emissions_100g_fat                 160 non-null    float64
 4   land_use_kg                        160 non-null    float64
 5   land_use_1000kcal                  160 non-null    float64
 6   Land use per 100 grams of protein  158 non-null    float64
 7   Land use per 100 grams of fat      160 non-null    float64
 8   Bananas index (kg)                 160 non-null    float64
 9   Bananas index (1000 kcalories)     160 non-null    float64
 10  Bananas index (100g protein)       160 non-null    float64
dtypes: float64(11)
memory usage: 15.0+ KB

In [29]:
banana.loc['Bananas', 'Bananas index (kg)']

1.0

In [30]:
banana.sort_values('Bananas index (kg)', ascending=False).head(10)

,emissions_kg,emissions_1000kcal,emissions_100g_protein,emissions_100g_fat,land_use_kg,land_use_1000kcal,Land use per 100 grams of protein,Land use per 100 grams of fat,Bananas index (kg),Bananas index (1000 kcalories),Bananas index (100g protein)
entity,,,,,,,,,,,
Beef steak,129.747715,68.095953,64.190391,146.107870,427.331126,223.690135,211.381205,478.803717,148.563324,77.752629,8.312805
Beef mince,95.034572,47.336598,53.111026,80.581707,295.253544,147.166781,162.955867,250.174427,108.816189,54.049393,6.878002
Beef meatballs,70.787474,31.338691,35.620428,52.661812,214.995398,94.463012,106.472397,157.280237,81.052853,35.782826,4.612929
Beef burger,53.976371,21.905134,28.806286,32.719983,135.347117,54.560874,71.225132,83.275825,61.803856,25.011498,3.730481
Lamb chops,30.901993,11.828168,17.188501,14.535445,43.660000,16.711250,24.284651,20.536132,35.383303,13.505518,2.225951
Lamb (leg),30.740947,15.182483,16.628529,23.442815,43.422118,21.444985,23.488031,33.112524,35.198904,17.335509,2.153433
Lamb burgers,26.928289,10.815351,15.773420,14.478753,38.097373,15.302500,22.316934,20.493202,30.833345,12.349074,2.042695
Cottage cheese,25.278503,29.346968,22.337566,244.477973,29.915060,34.694337,26.410036,288.289479,28.944313,33.508657,2.892767
Parmesan cheese,24.016480,6.369095,8.438339,8.307382,28.249496,7.495260,9.939259,9.773975,27.499275,7.272295,1.092785
Prawns,20.911283,26.329290,13.121885,348.489652,1.017165,1.065657,0.686572,12.960811,23.943772,30.063042,1.699315

In [32]:
banana.sort_values('Bananas index (1000 kcalories)', ascending=False).head(10)

,emissions_kg,emissions_1000kcal,emissions_100g_protein,emissions_100g_fat,land_use_kg,land_use_1000kcal,Land use per 100 grams of protein,Land use per 100 grams of fat,Bananas index (kg),Bananas index (1000 kcalories),Bananas index (100g protein)
entity,,,,,,,,,,,
Beef steak,129.747715,68.095953,64.190391,146.107870,427.331126,223.690135,211.381205,478.803717,148.563324,77.752629,8.312805
Beef mince,95.034572,47.336598,53.111026,80.581707,295.253544,147.166781,162.955867,250.174427,108.816189,54.049393,6.878002
Beef meatballs,70.787474,31.338691,35.620428,52.661812,214.995398,94.463012,106.472397,157.280237,81.052853,35.782826,4.612929
Cottage cheese,25.278503,29.346968,22.337566,244.477973,29.915060,34.694337,26.410036,288.289479,28.944313,33.508657,2.892767
Prawns,20.911283,26.329290,13.121885,348.489652,1.017165,1.065657,0.686572,12.960811,23.943772,30.063042,1.699315
Lettuce,4.926023,25.324299,39.949626,64.423953,6.781334,34.681560,54.330936,87.018948,5.640380,28.915534,5.173570
Raspberries,8.370972,24.614978,60.839171,186.986093,1.544836,4.542864,11.227628,34.509046,9.584904,28.105624,7.878815
Beef burger,53.976371,21.905134,28.806286,32.719983,135.347117,54.560874,71.225132,83.275825,61.803856,25.011498,3.730481
Lamb (leg),30.740947,15.182483,16.628529,23.442815,43.422118,21.444985,23.488031,33.112524,35.198904,17.335509,2.153433
Coconut milk,3.319990,12.848692,257.293857,28.268731,0.545269,2.216621,32.738749,4.415864,3.801444,14.670763,33.320155

In [33]:
banana.sort_values('Bananas index (100g protein)', ascending=False).head(10)

,emissions_kg,emissions_1000kcal,emissions_100g_protein,emissions_100g_fat,land_use_kg,land_use_1000kcal,Land use per 100 grams of protein,Land use per 100 grams of fat,Bananas index (kg),Bananas index (1000 kcalories),Bananas index (100g protein)
entity,,,,,,,,,,,
Coconut milk,3.319990,12.848692,257.293857,28.268731,0.545269,2.216621,32.738749,4.415864,3.801444,14.670763,33.320155
Sugar,1.851686,0.464977,159.733044,239.244524,2.153669,0.539469,198.893081,293.640795,2.120211,0.530915,20.685802
Grapes,8.278876,12.671419,116.820455,203.724449,1.536532,2.349845,21.639156,37.785507,9.479453,14.468351,15.128521
Beef steak,129.747715,68.095953,64.190391,146.107870,427.331126,223.690135,211.381205,478.803717,148.563324,77.752629,8.312805
Raspberries,8.370972,24.614978,60.839171,186.986093,1.544836,4.542864,11.227628,34.509046,9.584904,28.105624,7.878815
Beef mince,95.034572,47.336598,53.111026,80.581707,295.253544,147.166781,162.955867,250.174427,108.816189,54.049393,6.878002
Marmalade,1.548921,0.763164,50.158821,75.682636,1.730099,0.757672,54.982653,83.314984,1.773541,0.871388,6.495684
Butter,3.324503,1.165393,47.816151,1.414657,3.619797,1.250474,53.342141,1.500628,3.806612,1.330657,6.192303
Lettuce,4.926023,25.324299,39.949626,64.423953,6.781334,34.681560,54.330936,87.018948,5.640380,28.915534,5.173570
Beef meatballs,70.787474,31.338691,35.620428,52.661812,214.995398,94.463012,106.472397,157.280237,81.052853,35.782826,4.612929

These lists contain many of the same foods, but differ in key ways. When the denominator is a kilogram, all of the top entries are meats. When the denominator changes from a kilogram to a thousand calories, some fruits enter the top (higher density/calorie content).  When looking at 100g protein, sugar rises to the top due likely to its very low protein content.  The only food that appears in all three is beef.

In [34]:
banana[banana['Bananas index (kg)'] > 10]

,emissions_kg,emissions_1000kcal,emissions_100g_protein,emissions_100g_fat,land_use_kg,land_use_1000kcal,Land use per 100 grams of protein,Land use per 100 grams of fat,Bananas index (kg),Bananas index (1000 kcalories),Bananas index (100g protein)
entity,,,,,,,,,,,
Bacon,19.314209,6.818607,9.157925,11.273881,42.332229,14.792841,18.106127,23.911078,22.115095,7.785553,1.185973
Beef burger,53.976371,21.905134,28.806286,32.719983,135.347117,54.560874,71.225132,83.275825,61.803856,25.011498,3.730481
Beef meatballs,70.787474,31.338691,35.620428,52.661812,214.995398,94.463012,106.472397,157.280237,81.052853,35.782826,4.612929
Beef mince,95.034572,47.336598,53.111026,80.581707,295.253544,147.166781,162.955867,250.174427,108.816189,54.049393,6.878002
Beef steak,129.747715,68.095953,64.190391,146.107870,427.331126,223.690135,211.381205,478.803717,148.563324,77.752629,8.312805
Blue cheese,20.105753,6.113389,14.046817,7.243054,23.892146,7.249884,16.395390,8.581762,23.021427,6.980327,1.819096
Brie,19.139581,5.702704,10.609649,6.686894,22.454388,6.681748,12.449595,7.827718,21.915144,6.511404,1.373974
Camembert,16.281430,5.171893,10.084931,6.731054,19.044357,5.992492,11.663422,7.744435,18.642513,5.905319,1.306022
Cheddar cheese,20.749045,5.406193,8.721144,6.693239,24.451037,6.353026,11.783915,7.830016,23.758006,6.172845,1.129409
Chicken breast,9.272323,5.830486,4.518434,27.716290,9.220959,5.796039,4.493710,27.518737,10.616967,6.657307,0.585148
Chicken thighs,9.981881,5.095227,5.344501,7.672648,9.851754,5.023467,5.270620,7.568749,11.429423,5.817780,0.692125
Chicken wings,9.583456,4.650311,5.105153,6.969777,9.506970,4.613541,5.063860,6.938755,10.973219,5.309770,0.661129
Chilli con carne,13.540805,7.844403,17.688434,13.005458,28.304685,16.398791,36.975192,27.188393,15.504450,8.956816,2.290694
Cod,10.904109,8.560719,7.087446,74.485781,5.267857,3.974725,3.518976,32.139084,12.485389,9.774713,0.917841
Cod fish fingers,9.313182,4.701090,6.949603,11.205453,5.416458,2.706016,4.075833,6.432551,10.663750,5.367751,0.899990
Cottage cheese,25.278503,29.346968,22.337566,244.477973,29.915060,34.694337,26.410036,288.289479,28.944313,33.508657,2.892767
Dark chocolate,20.620037,3.691518,26.655503,4.471023,48.788233,9.642100,53.561114,18.080407,23.610290,4.215011,3.451950
Feta cheese,14.838609,5.042113,8.418578,5.984398,17.472121,5.934872,9.907002,7.044679,16.990458,5.757135,1.090225
Goat’s cheese,19.312073,6.220251,12.548149,7.478561,22.617936,7.295756,14.445831,8.773460,22.112650,7.102344,1.625015
Halloumi cheese,16.172452,5.282519,7.035951,7.141841,19.101111,6.247765,8.302601,8.456865,18.517731,6.031632,0.911172
Lamb (leg),30.740947,15.182483,16.628529,23.442815,43.422118,21.444985,23.488031,33.112524,35.198904,17.335509,2.153433
Lamb burgers,26.928289,10.815351,15.773420,14.478753,38.097373,15.302500,22.316934,20.493202,30.833345,12.349074,2.042695
Lamb chops,30.901993,11.828168,17.188501,14.535445,43.660000,16.711250,24.284651,20.536132,35.383303,13.505518,2.225951
Macaroni cheese,16.849313,5.245219,9.361866,7.742616,20.686935,6.597463,12.132912,10.102668,19.292748,5.989042,1.212383
Mackerel,13.606385,6.250301,7.133691,11.290381,5.801549,2.617001,3.054948,4.667267,15.579540,7.136655,0.923830
Milk chocolate,10.800275,2.210999,15.107684,4.808329,17.273874,3.564060,22.834012,8.021104,12.366497,2.524541,1.956480
Mozzarella cheese,16.233200,6.764520,8.797819,9.417882,19.061286,7.936335,10.341435,11.016421,18.587288,7.723795,1.139338
Parmesan cheese,24.016480,6.369095,8.438339,8.307382,28.249496,7.495260,9.939259,9.773975,27.499275,7.272295,1.092785
Pork chops,12.163891,4.588105,7.407893,5.900807,17.308312,6.422918,10.650062,8.198401,13.927860,5.238743,0.959339
Pork sausages,9.767878,3.660900,6.913241,5.448153,13.559548,5.112492,9.581818,7.713947,11.184385,4.180051,0.895281
Prawns,20.911283,26.329290,13.121885,348.489652,1.017165,1.065657,0.686572,12.960811,23.943772,30.063042,1.699315
Ricotta cheese,16.294974,5.201455,8.801847,6.620459,18.968722,6.017695,10.139899,7.649686,18.658020,5.939072,1.139860
Salmon,10.412581,5.953093,4.832165,13.164939,4.747958,2.707115,2.214772,5.940113,11.922582,6.797300,0.625777
Tuna,13.075355,9.969608,4.972586,105.113632,5.521840,4.194251,2.167108,44.058029,14.971502,11.383397,0.643961

In [37]:
banana[~(banana['Bananas index (kg)'] > 1)]

,emissions_kg,emissions_1000kcal,emissions_100g_protein,emissions_100g_fat,land_use_kg,land_use_1000kcal,Land use per 100 grams of protein,Land use per 100 grams of fat,Bananas index (kg),Bananas index (1000 kcalories),Bananas index (100g protein)
entity,,,,,,,,,,,
Ale,0.488690,0.317338,0.878525,2.424209,0.811485,0.601152,1.577687,3.065766,0.559558,0.362340,0.113771
Almond butter,0.387011,0.067265,0.207599,0.079103,7.683045,1.296870,3.608433,1.495297,0.443134,0.076804,0.026885
Almond milk,0.655888,2.222230,13.595512,4.057470,1.370106,2.675063,12.687839,4.600530,0.751002,2.537364,1.760651
Almonds,0.602368,0.105029,0.328335,0.119361,8.230927,1.423376,4.261040,1.610136,0.689721,0.119923,0.042520
Apple juice,0.458378,0.955184,29.152212,19.754980,0.660629,1.382839,43.232158,26.246743,0.524851,1.090638,3.775280
Apples,0.507354,0.898188,13.442716,25.594410,0.668999,1.205081,18.667990,36.386277,0.580929,1.025560,1.740863
Bagels,0.802813,0.329389,0.959624,3.741236,2.262947,0.924206,2.663544,10.173081,0.919234,0.376100,0.124274
Bananas,0.873350,0.875803,7.721869,20.469220,2.639824,2.717877,22.821229,64.907342,1.000000,1.000000,1.000000
Beer,0.686283,0.606472,1.509246,4.455620,0.827887,0.766329,2.069713,4.625173,0.785806,0.692475,0.195451
Coconut oil,0.528741,0.339007,9.821966,4.106947,0.734497,0.427187,14.175496,4.570065,0.605418,0.387081,1.271967
Courgettes,0.846479,3.254015,4.499813,16.354527,1.267480,4.761213,6.560221,24.104361,0.969233,3.715466,0.582736
Cucumber,0.847114,4.115565,7.338882,22.657421,1.080249,5.391894,9.537909,29.531063,0.969960,4.699193,0.950402
Frozen chips (french fries),0.753472,0.531024,3.822119,3.244333,2.105977,1.455530,10.762102,8.036323,0.862738,0.606329,0.494973
Frozen onion rings,0.771175,0.300218,1.891947,0.618079,2.103162,0.802711,5.195847,1.650925,0.883008,0.342791,0.245011
Frozen potato wedges,0.664775,0.480020,3.096824,4.353587,1.688861,1.216301,7.897629,9.015120,0.761179,0.548091,0.401046
Frozen sweet potato fries,0.409885,0.281673,2.641979,0.694194,1.967662,1.362967,12.579391,3.335497,0.469325,0.321617,0.342142
Lemons,0.470153,1.101691,4.813572,18.599275,0.611375,1.480950,6.255151,24.007351,0.538333,1.257922,0.623369
Limes,0.463008,1.420994,5.020169,18.861549,0.626187,1.998480,6.820544,25.442105,0.530152,1.622505,0.650124
Nut loaf,0.716131,0.495529,2.246645,0.820028,2.004030,1.385892,6.289355,2.291662,0.819982,0.565800,0.290946
Oat milk,0.453281,1.051135,6.718169,4.098738,0.526874,1.221709,7.813359,4.767600,0.519014,1.200196,0.870019
Onions,0.362860,1.014035,3.192865,12.702158,0.395357,1.089143,3.225629,13.388255,0.415481,1.157836,0.413483
Orange juice,0.488848,1.198713,9.279817,22.951580,0.705297,1.706871,12.984564,31.978453,0.559740,1.368702,1.201758
Oranges,0.466550,1.076517,4.971439,21.609950,0.666498,1.486787,6.945259,31.584671,0.534207,1.229178,0.643813
Pitta bread,0.563561,0.254204,0.745270,6.044426,1.804066,0.805656,2.328243,19.381761,0.645287,0.290253,0.096514
Potatoes,0.207276,0.232124,1.157598,7.651273,0.804449,0.952186,4.672538,36.574749,0.237335,0.265042,0.149912
Sourdough bread,0.851167,0.344747,1.242905,4.523647,2.371923,0.969474,3.681614,13.151977,0.974601,0.393636,0.160959

In [38]:
banana[banana['Bananas index (kg)'] < 1]

,emissions_kg,emissions_1000kcal,emissions_100g_protein,emissions_100g_fat,land_use_kg,land_use_1000kcal,Land use per 100 grams of protein,Land use per 100 grams of fat,Bananas index (kg),Bananas index (1000 kcalories),Bananas index (100g protein)
entity,,,,,,,,,,,
Ale,0.488690,0.317338,0.878525,2.424209,0.811485,0.601152,1.577687,3.065766,0.559558,0.362340,0.113771
Almond butter,0.387011,0.067265,0.207599,0.079103,7.683045,1.296870,3.608433,1.495297,0.443134,0.076804,0.026885
Almond milk,0.655888,2.222230,13.595512,4.057470,1.370106,2.675063,12.687839,4.600530,0.751002,2.537364,1.760651
Almonds,0.602368,0.105029,0.328335,0.119361,8.230927,1.423376,4.261040,1.610136,0.689721,0.119923,0.042520
Apple juice,0.458378,0.955184,29.152212,19.754980,0.660629,1.382839,43.232158,26.246743,0.524851,1.090638,3.775280
Apples,0.507354,0.898188,13.442716,25.594410,0.668999,1.205081,18.667990,36.386277,0.580929,1.025560,1.740863
Bagels,0.802813,0.329389,0.959624,3.741236,2.262947,0.924206,2.663544,10.173081,0.919234,0.376100,0.124274
Beer,0.686283,0.606472,1.509246,4.455620,0.827887,0.766329,2.069713,4.625173,0.785806,0.692475,0.195451
Coconut oil,0.528741,0.339007,9.821966,4.106947,0.734497,0.427187,14.175496,4.570065,0.605418,0.387081,1.271967
Courgettes,0.846479,3.254015,4.499813,16.354527,1.267480,4.761213,6.560221,24.104361,0.969233,3.715466,0.582736
Cucumber,0.847114,4.115565,7.338882,22.657421,1.080249,5.391894,9.537909,29.531063,0.969960,4.699193,0.950402
Frozen chips (french fries),0.753472,0.531024,3.822119,3.244333,2.105977,1.455530,10.762102,8.036323,0.862738,0.606329,0.494973
Frozen onion rings,0.771175,0.300218,1.891947,0.618079,2.103162,0.802711,5.195847,1.650925,0.883008,0.342791,0.245011
Frozen potato wedges,0.664775,0.480020,3.096824,4.353587,1.688861,1.216301,7.897629,9.015120,0.761179,0.548091,0.401046
Frozen sweet potato fries,0.409885,0.281673,2.641979,0.694194,1.967662,1.362967,12.579391,3.335497,0.469325,0.321617,0.342142
Lemons,0.470153,1.101691,4.813572,18.599275,0.611375,1.480950,6.255151,24.007351,0.538333,1.257922,0.623369
Limes,0.463008,1.420994,5.020169,18.861549,0.626187,1.998480,6.820544,25.442105,0.530152,1.622505,0.650124
Nut loaf,0.716131,0.495529,2.246645,0.820028,2.004030,1.385892,6.289355,2.291662,0.819982,0.565800,0.290946
Oat milk,0.453281,1.051135,6.718169,4.098738,0.526874,1.221709,7.813359,4.767600,0.519014,1.200196,0.870019
Onions,0.362860,1.014035,3.192865,12.702158,0.395357,1.089143,3.225629,13.388255,0.415481,1.157836,0.413483
Orange juice,0.488848,1.198713,9.279817,22.951580,0.705297,1.706871,12.984564,31.978453,0.559740,1.368702,1.201758
Oranges,0.466550,1.076517,4.971439,21.609950,0.666498,1.486787,6.945259,31.584671,0.534207,1.229178,0.643813
Pitta bread,0.563561,0.254204,0.745270,6.044426,1.804066,0.805656,2.328243,19.381761,0.645287,0.290253,0.096514
Potatoes,0.207276,0.232124,1.157598,7.651273,0.804449,0.952186,4.672538,36.574749,0.237335,0.265042,0.149912
Sourdough bread,0.851167,0.344747,1.242905,4.523647,2.371923,0.969474,3.681614,13.151977,0.974601,0.393636,0.160959

In [42]:
twocondition = banana[(banana['Bananas index (kg)'] > 5) & (banana['Bananas index (100g protein)'] < 1)].copy()
twocondition.sort_values('Bananas index (kg)')

,emissions_kg,emissions_1000kcal,emissions_100g_protein,emissions_100g_fat,land_use_kg,land_use_1000kcal,Land use per 100 grams of protein,Land use per 100 grams of fat,Bananas index (kg),Bananas index (1000 kcalories),Bananas index (100g protein)
entity,,,,,,,,,,,
Eggs,4.436600,2.765086,3.143945,3.959905,6.824729,4.365401,5.072666,6.293576,5.079982,3.157203,0.407148
Olive oil,5.184628,0.591959,NaN,0.523292,21.707958,2.478318,NaN,2.190833,5.936487,0.675905,0.000000
Chicken burger,5.434487,2.329615,3.661770,4.582128,6.053407,2.560246,4.219893,5.090691,6.222579,2.659977,0.474208
Cod fishcakes,7.815675,5.021886,6.541612,12.267606,3.808558,2.383748,3.272294,5.796482,8.949080,5.734039,0.847154
Chicken sausages,8.164302,4.020155,5.400881,6.917650,8.330555,4.074470,5.523113,6.976656,9.348264,4.590252,0.699427
Chicken breast,9.272323,5.830486,4.518434,27.716290,9.220959,5.796039,4.493710,27.518737,10.616967,6.657307,0.585148
Cod fish fingers,9.313182,4.701090,6.949603,11.205453,5.416458,2.706016,4.075833,6.432551,10.663750,5.367751,0.899990
Chicken wings,9.583456,4.650311,5.105153,6.969777,9.506970,4.613541,5.063860,6.938755,10.973219,5.309770,0.661129
Pork sausages,9.767878,3.660900,6.913241,5.448153,13.559548,5.112492,9.581818,7.713947,11.184385,4.180051,0.895281
Chicken thighs,9.981881,5.095227,5.344501,7.672648,9.851754,5.023467,5.270620,7.568749,11.429423,5.817780,0.692125
Salmon,10.412581,5.953093,4.832165,13.164939,4.747958,2.707115,2.214772,5.940113,11.922582,6.797300,0.625777
Cod,10.904109,8.560719,7.087446,74.485781,5.267857,3.974725,3.518976,32.139084,12.485389,9.774713,0.917841
Pork chops,12.163891,4.588105,7.407893,5.900807,17.308312,6.422918,10.650062,8.198401,13.927860,5.238743,0.959339
Tuna,13.075355,9.969608,4.972586,105.113632,5.521840,4.194251,2.167108,44.058029,14.971502,11.383397,0.643961
Mackerel,13.606385,6.250301,7.133691,11.290381,5.801549,2.617001,3.054948,4.667267,15.579540,7.136655,0.923830
Halloumi cheese,16.172452,5.282519,7.035951,7.141841,19.101111,6.247765,8.302601,8.456865,18.517731,6.031632,0.911172

The foods at the top of the columns above are all high protein foods