# Day 3: Session 3C - The Top-N Pattern

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/3c_sorting_and_ranking.html)

Date: 09/02/2026

In [1]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'
goleta = pd.read_csv(url)

pm25 = goleta[goleta['parameter'] == 'pm25'].copy()
pm25.shape

(734, 15)

In [2]:
pm25.sort_values('value').head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1691,1186,Goleta,pm25,-4.0,µg/m³,2024-07-31T11:00:00+00:00,2024-07-31T04:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1713,1186,Goleta,pm25,-3.0,µg/m³,2024-08-01T09:00:00+00:00,2024-08-01T02:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1428,1186,Goleta,pm25,-3.0,µg/m³,2024-07-20T12:00:00+00:00,2024-07-20T05:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1429,1186,Goleta,pm25,-3.0,µg/m³,2024-07-20T13:00:00+00:00,2024-07-20T06:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1716,1186,Goleta,pm25,-3.0,µg/m³,2024-08-01T12:00:00+00:00,2024-08-01T05:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [3]:
pm25.sort_values('value', ascending=False).head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1376,1186,Goleta,pm25,22.0,µg/m³,2024-07-18T08:00:00+00:00,2024-07-18T01:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1712,1186,Goleta,pm25,22.0,µg/m³,2024-08-01T08:00:00+00:00,2024-08-01T01:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1873,1186,Goleta,pm25,21.0,µg/m³,2024-08-08T08:00:00+00:00,2024-08-08T01:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1930,1186,Goleta,pm25,20.0,µg/m³,2024-08-10T17:00:00+00:00,2024-08-10T10:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1838,1186,Goleta,pm25,19.0,µg/m³,2024-08-06T20:00:00+00:00,2024-08-06T13:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [6]:
goleta.sort_values('parameter', ascending = False).head(3)

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1961,1186,Goleta,pm25,5.0,µg/m³,2024-08-12T00:00:00+00:00,2024-08-11T17:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1479,1186,Goleta,pm25,6.0,µg/m³,2024-07-22T15:00:00+00:00,2024-07-22T08:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1477,1186,Goleta,pm25,4.0,µg/m³,2024-07-22T13:00:00+00:00,2024-07-22T06:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [7]:
goleta['parameter'].unique()

array(['o3', 'pm10', 'pm25'], dtype=object)

In [5]:
pm25.head(3)

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1228,1186,Goleta,pm25,3.0,µg/m³,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1229,1186,Goleta,pm25,8.0,µg/m³,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1230,1186,Goleta,pm25,6.0,µg/m³,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [9]:
pm25.sort_values('datetimeLocal').head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1228,1186,Goleta,pm25,3.0,µg/m³,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1229,1186,Goleta,pm25,8.0,µg/m³,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1230,1186,Goleta,pm25,6.0,µg/m³,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1231,1186,Goleta,pm25,4.0,µg/m³,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1232,1186,Goleta,pm25,9.0,µg/m³,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [ ]:
babbanananapm25.sort_values('value', ascending=False).head(10)

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1376,1186,Goleta,pm25,22.0,µg/m³,2024-07-18T08:00:00+00:00,2024-07-18T01:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1712,1186,Goleta,pm25,22.0,µg/m³,2024-08-01T08:00:00+00:00,2024-08-01T01:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1873,1186,Goleta,pm25,21.0,µg/m³,2024-08-08T08:00:00+00:00,2024-08-08T01:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1930,1186,Goleta,pm25,20.0,µg/m³,2024-08-10T17:00:00+00:00,2024-08-10T10:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1838,1186,Goleta,pm25,19.0,µg/m³,2024-08-06T20:00:00+00:00,2024-08-06T13:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1863,1186,Goleta,pm25,19.0,µg/m³,2024-08-07T22:00:00+00:00,2024-08-07T15:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1534,1186,Goleta,pm25,17.0,µg/m³,2024-07-24T22:00:00+00:00,2024-07-24T15:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1592,1186,Goleta,pm25,17.0,µg/m³,2024-07-27T08:00:00+00:00,2024-07-27T01:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1839,1186,Goleta,pm25,16.0,µg/m³,2024-08-06T21:00:00+00:00,2024-08-06T14:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1954,1186,Goleta,pm25,16.0,µg/m³,2024-08-11T17:00:00+00:00,2024-08-11T10:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [11]:
pm25.sort_values('value', ascending=False).head(10)[['datetimeLocal', 'value', 'unit']]

                  datetimeLocal  value   unit
1376  2024-07-18T01:00:00-07:00   22.0  µg/m³
1712  2024-08-01T01:00:00-07:00   22.0  µg/m³
1873  2024-08-08T01:00:00-07:00   21.0  µg/m³
1930  2024-08-10T10:00:00-07:00   20.0  µg/m³
1838  2024-08-06T13:00:00-07:00   19.0  µg/m³
1863  2024-08-07T15:00:00-07:00   19.0  µg/m³
1534  2024-07-24T15:00:00-07:00   17.0  µg/m³
1592  2024-07-27T01:00:00-07:00   17.0  µg/m³
1839  2024-08-06T14:00:00-07:00   16.0  µg/m³
1954  2024-08-11T10:00:00-07:00   16.0  µg/m³

In [13]:
pm25.sort_values('value').head(5)[['datetimeLocal', 'value', 'unit']]

                  datetimeLocal  value   unit
1691  2024-07-31T04:00:00-07:00   -4.0  µg/m³
1713  2024-08-01T02:00:00-07:00   -3.0  µg/m³
1428  2024-07-20T05:00:00-07:00   -3.0  µg/m³
1429  2024-07-20T06:00:00-07:00   -3.0  µg/m³
1716  2024-08-01T05:00:00-07:00   -3.0  µg/m³

In [17]:
# Filter first and then rank
goleta[goleta['parameter'] == 'pm25'].sort_values('value', ascending=False).head(5)[
    ['datetimeLocal', 'value', 'unit']
]
# Why?  Particulates and ozone are measured in different units, so 
# the values in the 'values' column arent comparable unless 
# filtered to only one pollutant.

                  datetimeLocal  value   unit
1376  2024-07-18T01:00:00-07:00   22.0  µg/m³
1712  2024-08-01T01:00:00-07:00   22.0  µg/m³
1873  2024-08-08T01:00:00-07:00   21.0  µg/m³
1930  2024-08-10T10:00:00-07:00   20.0  µg/m³
1838  2024-08-06T13:00:00-07:00   19.0  µg/m³

In [ ]:
# .idxmax gives the index label of the largest value in a column
# i.e. "index max"
worst_hour = pm25['value'].idxmax()
pm25.loc[worst_hour, 'datetimeLocal']

'2024-07-18T01:00:00-07:00'

In [ ]:
# idxmin = index minimum - gives index label of smallest
# value in column
cleanest_hour = pm25['value'].idxmin()
print(cleanest_hour)
print(pm25.loc[cleanest_hour, 'datetimeLocal'])
print(pm25.loc[cleanest_hour, 'value'])

1691
2024-07-31T04:00:00-07:00
-4.0

In [23]:
# .copy()
# creates a new table so that you can keep and modify a filtered result
# this way, you are no longer tied to the original table

pm10 = goleta[goleta['parameter'] == 'pm10'].copy()

In [ ]:
worst_ten = pm10.sort_values('value', ascending=False).head(10)
worst_ten[['datetimeLocal', 'value', 'unit']]
print("Worst pm10 hour")

                  datetimeLocal  value   unit
1086  2024-08-05T17:00:00-07:00   40.0  µg/m³
795   2024-07-24T14:00:00-07:00   38.0  µg/m³
796   2024-07-24T15:00:00-07:00   36.0  µg/m³
1105  2024-08-06T14:00:00-07:00   36.0  µg/m³
1084  2024-08-05T15:00:00-07:00   36.0  µg/m³
1103  2024-08-06T12:00:00-07:00   35.0  µg/m³
1126  2024-08-07T12:00:00-07:00   34.0  µg/m³
1195  2024-08-10T09:00:00-07:00   34.0  µg/m³
848   2024-07-26T19:00:00-07:00   34.0  µg/m³
1077  2024-08-05T08:00:00-07:00   33.0  µg/m³