# Day 3: Session 3A - Booleans & Conditionals

Date: 09/02/2026

In [105]:
import pandas as pd

In [106]:
url = 'https://eds-217-essential-python.github.io/data/toolik_weather.csv'

In [107]:
toolik = pd.read_csv(url)

## 1. A yes-or-no question

In [108]:
temperature = 8.4

In [109]:
temperature > 0

True

In [110]:
type(temperature > 0)

bool

In [111]:
above_freezing = temperature > 0

In [112]:
above_freezing

True

In [113]:
toolik['Daily_AirTemp_Mean_C']

0         8.4
1         6.0
2         5.8
3         1.8
4         6.8
         ...
11166   -21.2
11167   -24.2
11168   -21.1
11169   -17.3
11170    -5.5
Name: Daily_AirTemp_Mean_C, Length: 11171, dtype: float64

In [114]:
# How to find a specific row in a data frame
toolik.loc[[0,1,2]]

,Year,Month,Date,LTER_Site,Station,Daily_AirTemp_Mean_C,Flag_Daily_AirTemp_Mean_C,Daily_AirTemp_AbsMax_C,Flag_Daily_AirTemp_AbsMax_C,Daily_AirTemp_AbsMin_C,...,Daily_Precip_Total_mm,Flag_Daily_Precip_Total_mm,Daily_windsp_mean_msec,FLAG_Daily_windsp_mean_msec,Daily_Windspeed_AbsMax_m_s,Daily_globalrad_total_jcm2,FLAG_Daily_globalrad_total_mjm2,Moss,Soil20cm,Comments
0,1988,6,19880601,ARC,TLKMAIN,8.4,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...
1,1988,6,19880602,ARC,TLKMAIN,6.0,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...
2,1988,6,19880603,ARC,TLKMAIN,5.8,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...

In [115]:
# another method
rows_wanted = [0,1,2]
toolik.loc[rows_wanted]

,Year,Month,Date,LTER_Site,Station,Daily_AirTemp_Mean_C,Flag_Daily_AirTemp_Mean_C,Daily_AirTemp_AbsMax_C,Flag_Daily_AirTemp_AbsMax_C,Daily_AirTemp_AbsMin_C,...,Daily_Precip_Total_mm,Flag_Daily_Precip_Total_mm,Daily_windsp_mean_msec,FLAG_Daily_windsp_mean_msec,Daily_Windspeed_AbsMax_m_s,Daily_globalrad_total_jcm2,FLAG_Daily_globalrad_total_mjm2,Moss,Soil20cm,Comments
0,1988,6,19880601,ARC,TLKMAIN,8.4,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...
1,1988,6,19880602,ARC,TLKMAIN,6.0,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...
2,1988,6,19880603,ARC,TLKMAIN,5.8,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...

In [116]:
# to just get a single column:
toolik.loc[0, 'Daily_AirTemp_Mean_C']

8.4

## 2. The comparison operators

In [117]:
print(temperature > 0)
print(temperature < 0)
print(temperature >= 0)
print(temperature <= 0)
print(temperature == 8.4)
# == is comparison, and = is assignment!
print(temperature != 8.4)

True
False
True
False
True
False

In [118]:
print(toolik.loc[0, 'Station'])
print(toolik.loc[0, 'Station'] == 'TLKMAIN')

TLKMAIN
True

## 3. Asking two questions at once

In [119]:
temperature = 8.4
precipitation = 0.0
print(temperature > 0 and precipitation == 0.0)
# true when both sides are true
print(temperature == 8.4 and precipitation > 0)
print(temperature == 8.4 or precipitation > 10)
# true when one side is true
print(not temperature > 0)
# flips the answer

True
False
True
False

## 4. if / elif / else

In [120]:
temperature = 8.4
if temperature > 0:
    print ("Above Freezing")

print("Hello")

Above Freezing
Hello

In [121]:
temperature = 8.4
if temperature < 0:
    print ("Below Freezing")

print("Hello")

Hello

In [122]:
if temperature > 0:
    print ("Above Freezing")
else:
        print("Below Freezing")

Above Freezing

In [123]:
temperature = 12.0

if temperature > 10:
    category = 'mild'
elif temperature > 0:
    category = 'cool'
else:
    category = 'cold'

print(category)

mild

## 5. Asking a whole column

In [124]:
for value in toolik.loc[[0, 1, 2], 'Daily_AirTemp_Mean_C']:
    print(value)
    if value > 7:
        print(f"{value} is warm")
    elif value > 0:
        print(f"{value} is mild")
    else:
        print(f"{value} is cold")

8.4
8.4 is warm
6.0
6.0 is mild
5.8
5.8 is mild

In [125]:
# a whole column at once

toolik['Daily_AirTemp_Mean_C'] > 0

0         True
1         True
2         True
3         True
4         True
         ...
11166    False
11167    False
11168    False
11169    False
11170    False
Name: Daily_AirTemp_Mean_C, Length: 11171, dtype: bool

In [126]:
# Rules for logical operators and Data Frames / Series
# 1. Wrap every conditional in parantheses
# 2. When dong "ands" and "ors", we switch to "&" and "|"

toolik['Daily_AirTemp_Mean_C'] > 0
toolik['Daily_Precip_Total_mm'] == 0

0         True
1         True
2         True
3         True
4        False
         ...
11166     True
11167     True
11168    False
11169     True
11170    False
Name: Daily_Precip_Total_mm, Length: 11171, dtype: bool

In [130]:
warm_and_dry = (toolik['Daily_AirTemp_Mean_C'] > 0) & (toolik['Daily_Precip_Total_mm'] == 0)
print(warm_and_dry)

0         True
1         True
2         True
3         True
4        False
         ...
11166    False
11167    False
11168    False
11169    False
11170    False
Length: 11171, dtype: bool

## 6. Counting the Trues

In [128]:
above_zero = toolik['Daily_AirTemp_Mean_C'] > 0
above_zero.sum()

3817

In [129]:
print(above_zero.sum() / toolik.shape[0])
print(above_zero.sum() / len(toolik))
print(sum(above_zero) / len(toolik))

0.34168830006266226
0.34168830006266226
0.34168830006266226

## 7. Where this goes next