# Day 2: Session 2A - Reading Data into pandas

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/2a_reading_data.html)

Date: 09/01/2026

In [156]:
import pandas as pd

In [157]:
url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'

In [158]:
goleta = pd.read_csv(url)

In [159]:
goleta.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [160]:
santa_barbara = pd.read_csv('https://eds-217-essential-python.github.io/data/openaq_santa_barbara_measurments.csv')

DataFrames and Series

In [161]:
goleta['value']

0        0.025
1        0.028
2        0.029
3        0.027
4        0.026
         ...
1957    10.000
1958     8.000
1959     8.000
1960     9.000
1961     5.000
Name: value, Length: 1962, dtype: float64

In [162]:
print(type(goleta))
print(type(goleta['value']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [163]:
goleta['value'].head()

0    0.025
1    0.028
2    0.029
3    0.027
4    0.026
Name: value, dtype: float64

In [164]:
goleta['parameter']

0         o3
1         o3
2         o3
3         o3
4         o3
        ...
1957    pm25
1958    pm25
1959    pm25
1960    pm25
1961    pm25
Name: parameter, Length: 1962, dtype: object

In [165]:
goleta['parameter'].head()

0    o3
1    o3
2    o3
3    o3
4    o3
Name: parameter, dtype: object

In [166]:
type(goleta['parameter'])

pandas.core.series.Series

Column names as a list

In [167]:
goleta.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit', 'datetimeUtc',
       'datetimeLocal', 'timezone', 'latitude', 'longitude', 'country_iso', 'isMobile',
       'isMonitor', 'owner_name', 'provider'],
      dtype='object')

In [168]:
column_names = goleta.columns.tolist()
column_names

['location_id',
 'location_name',
 'parameter',
 'value',
 'unit',
 'datetimeUtc',
 'datetimeLocal',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']

In [169]:
parameters_we_care_about = ['o3', 'pm25']
parameters_we_care_about

['o3', 'pm25']

In [170]:
print(column_names[0])
print(column_names[1])

location_id
location_name

In [171]:
len(column_names)

15

In [172]:
column_names[-1]

'provider'

Selecting columns with a list

In [173]:
keep = ['location_name', 'parameter', 'value', 'unit']
goleta[keep].head()

  location_name parameter  value unit
0        Goleta        o3  0.025  ppm
1        Goleta        o3  0.028  ppm
2        Goleta        o3  0.029  ppm
3        Goleta        o3  0.027  ppm
4        Goleta        o3  0.026  ppm

In [174]:
goleta[['location_name', 'parameter', 'value', 'unit']].head()

  location_name parameter  value unit
0        Goleta        o3  0.025  ppm
1        Goleta        o3  0.028  ppm
2        Goleta        o3  0.029  ppm
3        Goleta        o3  0.027  ppm
4        Goleta        o3  0.026  ppm

In [175]:
time_columns = ['datetimeUtc' 'datetimeLocal']

In [176]:
goleta_by_time = pd.read_csv(url, index_col='datetimeLocal')
goleta_by_time.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
datetimeLocal,,,,,,,,,,,,,,
2024-07-11T18:00:00-07:00,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-11T19:00:00-07:00,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-11T20:00:00-07:00,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-11T21:00:00-07:00,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-11T22:00:00-07:00,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [177]:
goleta_by_time.columns.tolist()

['location_id',
 'location_name',
 'parameter',
 'value',
 'unit',
 'datetimeUtc',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']

In [178]:
goleta_by_time = pd.read_csv(url, index_col='datetimeUtc')
goleta_by_time.head()

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
datetimeUtc,,,,,,,,,,,,,,
2024-07-12T01:00:00+00:00,1186,Goleta,o3,0.025,ppm,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T02:00:00+00:00,1186,Goleta,o3,0.028,ppm,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T03:00:00+00:00,1186,Goleta,o3,0.029,ppm,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T04:00:00+00:00,1186,Goleta,o3,0.027,ppm,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T05:00:00+00:00,1186,Goleta,o3,0.026,ppm,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

# Day 2: Session 2B - Exploring a DataFrame

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/2b_exploring_data.html)

Date: 09/01/2026

In [179]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'
goleta = pd.read_csv(url)

In [180]:
goleta.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [181]:
goleta.tail()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1957,1186,Goleta,pm25,10.0,µg/m³,2024-08-11T20:00:00+00:00,2024-08-11T13:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1958,1186,Goleta,pm25,8.0,µg/m³,2024-08-11T21:00:00+00:00,2024-08-11T14:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1959,1186,Goleta,pm25,8.0,µg/m³,2024-08-11T22:00:00+00:00,2024-08-11T15:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1960,1186,Goleta,pm25,9.0,µg/m³,2024-08-11T23:00:00+00:00,2024-08-11T16:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1961,1186,Goleta,pm25,5.0,µg/m³,2024-08-12T00:00:00+00:00,2024-08-11T17:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [182]:
goleta.head(3)

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [183]:
goleta.shape

(1962, 15)

In [184]:
print("rows:", goleta.shape[0])
print("columns:", goleta.shape[1])

rows: 1962
columns: 15

In [185]:
goleta.columns.tolist()

['location_id',
 'location_name',
 'parameter',
 'value',
 'unit',
 'datetimeUtc',
 'datetimeLocal',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']

In [186]:
goleta.dtypes

location_id        int64
location_name     object
parameter         object
value            float64
unit              object
datetimeUtc       object
datetimeLocal     object
timezone          object
latitude         float64
longitude        float64
country_iso      float64
isMobile         float64
isMonitor        float64
owner_name        object
provider          object
dtype: object

In [187]:
goleta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1962 entries, 0 to 1961
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    1962 non-null   int64
 1   location_name  1962 non-null   object
 2   parameter      1962 non-null   object
 3   value          1962 non-null   float64
 4   unit           1962 non-null   object
 5   datetimeUtc    1962 non-null   object
 6   datetimeLocal  1962 non-null   object
 7   timezone       1962 non-null   object
 8   latitude       1962 non-null   float64
 9   longitude      1962 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     1962 non-null   object
 14  provider       1962 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 230.1+ KB

In [188]:
goleta.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      1962
isMobile         1962
isMonitor        1962
owner_name          0
provider            0
dtype: int64

In [189]:
goleta.describe()

       location_id        value      latitude     longitude  country_iso  isMobile  isMonitor
count       1962.0  1962.000000  1.962000e+03  1.962000e+03          0.0       0.0        0.0
mean        1186.0     6.378173  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
std            0.0     7.313763  2.132172e-14  2.842896e-14          NaN       NaN        NaN
min         1186.0    -4.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
25%         1186.0     0.027000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
50%         1186.0     5.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
75%         1186.0    10.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
max         1186.0    40.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN

In [190]:
goleta['unit'].value_counts()

unit
µg/m³    1251
ppm       711
Name: count, dtype: int64

for the above cell, Some rows are in micrograms per cubic metre and some are in parts per million. The mean of 6.4 was computed by averaging those two units together, so it does not describe any real quantity that anyone measured in Goleta.

In [191]:
print(goleta['longitude'].value_counts())

longitude
-119.827797    1962
Name: count, dtype: int64

In [192]:
goleta['parameter'].value_counts()

parameter
pm25    734
o3      711
pm10    517
Name: count, dtype: int64

In [193]:
goleta['location_name'].value_counts()

location_name
Goleta    1962
Name: count, dtype: int64

In [194]:
list_of_counts = goleta['datetimeLocal'].value_counts().to_list()

In [195]:
new_names = {
    'datetimeUtc': 'datetime_utc',
    'datetimeLocal': 'datetime_local',
}
new_names

{'datetimeUtc': 'datetime_utc', 'datetimeLocal': 'datetime_local'}

In [196]:
new_names['datetimeUtc']

'datetime_utc'

In [197]:
goleta_renamed = goleta.rename(columns=new_names)
goleta_renamed.columns.tolist()

['location_id',
 'location_name',
 'parameter',
 'value',
 'unit',
 'datetime_utc',
 'datetime_local',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']