# Day 5: Session 5B - Several Answers at Once

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/5b_aggregating_data.html)

Date: 09/04/2026

In [1]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/national_parks.csv'
parks = pd.read_csv(url)

# Remove the rows that have park Totals in them and make a new dataframe:
by_year = parks[~(parks['year'] == 'Total')]
national_parks = by_year[by_year['unit_type'] == 'National Park'].copy()

national_parks.shape

(4682, 12)

In [2]:
national_parks.groupby('region')['visitors'].mean()

region
AK    1.204881e+05
IM    7.931557e+05
MW    6.108661e+05
NC    5.107866e+05
NE    1.618013e+06
PW    6.627740e+05
SE    1.572087e+06
Name: visitors, dtype: float64

In [3]:
national_parks.groupby('region')['visitors'].count()

region
AK     488
IM    1590
MW     533
NC      46
NE     179
PW    1393
SE     453
Name: visitors, dtype: int64

In [4]:
# .agg() removes the eye-matching by allowing you to do more than one calculation at a time
# Give it a list of aggregation names and it runs all of them on the same grouping and 
# puts the answers side by side:

national_parks.groupby('region')['visitors'].agg(['count', 'mean', 'max'])

# the result is a data frame rather than a series

        count          mean         max
region
AK        488  1.204881e+05    592431.0
IM       1590  7.931557e+05   5969811.0
MW        533  6.108661e+05   3527837.0
NC         46  5.107866e+05    680862.0
NE        179  1.618013e+06   5440952.0
PW       1393  6.627740e+05   5028868.0
SE        453  1.572087e+06  11312786.0

In [5]:
# Group national_parks by state and use .agg() with a list to get the count, mean and max of visitors. 
# Find a state whose mean looks impressive, but which is based on a limited sample number.

national_parks.groupby('state')['visitors'].agg(['count', 'mean', 'max'])

# Ohio has an impressively high mean, but based only on 39 samples

       count          mean         max
state
AK       488  1.204881e+05    592431.0
AR       109  8.443021e+05   2092400.0
AS        13  8.745692e+03     28892.0
AZ       290  1.009639e+06   5969811.0
CA       789  6.076323e+05   5028868.0
CO       378  6.353273e+05   4517585.0
FL       194  3.961249e+05   1534328.0
HI       153  8.838688e+05   2247974.0
KY        81  1.046299e+06   2396234.0
ME        98  1.668492e+06   5440952.0
MI        77  1.391706e+04     31760.0
MN        41  2.161420e+05    266935.0
MT       106  9.908449e+05   2946681.0
NC        86  6.069152e+06  11312786.0
ND        76  4.142048e+05    998849.0
NM        93  4.702549e+05    876500.0
NV        83  4.543101e+04    144846.0
OH        39  2.093105e+06   3527837.0
OR       113  3.068096e+05    756344.0
SC        32  8.217781e+04    143843.0
SD       191  5.786315e+05   1518396.0
TX       119  1.935455e+05    398583.0
UT       403  5.792425e+05   4295127.0
VA       127  1.178018e+06   2789100.0
VI        60  4.330022e+05    838684.0
WA       242  1.115853e+06   3846709.0
WY       201  1.606659e+06   4257177.0

In [6]:
# Several columns, summarised differently:

# for example: take the mean of this column, the sum of that one, 
# the number of distinct values in a third, etc.

# we do not select a single column, instead we run .agg() against the groupby object
# and we use a dictionary of "'column': 'function'"" pairs

# the result has one column per key, named after the key.

national_parks.groupby('region').agg({
    'visitors': 'mean',
    'unit_name': 'nunique',
    'year': 'min'
})

            visitors  unit_name  year
region
AK      1.204881e+05          9  1922
IM      7.931557e+05         18  1904
MW      6.108661e+05          7  1904
NC      5.107866e+05          1  1971
NE      1.618013e+06          2  1919
PW      6.627740e+05         17  1904
SE      1.572087e+06          7  1931

In [7]:
# Write one .agg() call, grouped by region, that reports the median number of visitors, 
# the latest year of record, and the number of distinct states in each region. 
# Why might the median be the more honest of the two averages for this data?

national_parks.groupby('region').agg({
    'visitors': 'median',
    'state': 'nunique',
    'year': 'max'
})

         visitors  state  year
region
AK        24595.0      1  2016
IM       378050.0      7  2016
MW       404700.0      6  2016
NC       538297.0      1  2016
NE      1699228.0      2  2016
PW       407653.0      6  2016
SE       513397.0      5  2016

In [8]:
# Ranking a grouped result


national_parks.groupby('unit_name')['visitors'].mean().sort_values(ascending=False).head(10)

unit_name
Great Smoky Mountains National Park    6.069152e+06
Grand Canyon National Park             2.096805e+06
Cuyahoga Valley National Park          2.093105e+06
Olympic National Park                  1.960219e+06
Rocky Mountain National Park           1.765457e+06
Yosemite National Park                 1.715356e+06
Grand Teton National Park              1.680664e+06
Acadia National Park                   1.668492e+06
Shenandoah National Park               1.556940e+06
Yellowstone National Park              1.549028e+06
Name: visitors, dtype: float64

In [9]:
park_stats = national_parks.groupby('unit_name')['visitors'].agg(['count', 'mean', 'max'])

park_stats.sort_values('mean', ascending=False).head(10)

                                     count          mean         max
unit_name
Great Smoky Mountains National Park     86  6.069152e+06  11312786.0
Grand Canyon National Park              98  2.096805e+06   5969811.0
Cuyahoga Valley National Park           39  2.093105e+06   3527837.0
Olympic National Park                   82  1.960219e+06   3846709.0
Rocky Mountain National Park           102  1.765457e+06   4517585.0
Yosemite National Park                 111  1.715356e+06   5028868.0
Grand Teton National Park               88  1.680664e+06   3352500.0
Acadia National Park                    98  1.668492e+06   5440952.0
Shenandoah National Park                81  1.556940e+06   2789100.0
Yellowstone National Park              113  1.549028e+06   4257177.0

In [10]:
# Filter national_parks to the single year '2016', then group by state and use .agg() to report 
# the count and mean of visitors. Rank the result by mean. 
# Compare the top three states with the all-time ranking by state from the earlier exercise, 
# the one that asked for count, mean and max. Did anything move? 


parks_2016 = national_parks[national_parks['year'] == '2016']

stats_2016 = parks_2016.groupby('state')['visitors'].agg(['count', 'mean'])
stats_2016.sort_values('mean', ascending=False).head(10)

       count          mean
state
NC         1  1.131279e+07
WY         2  3.763626e+06
ME         1  3.303393e+06
MT         1  2.946681e+06
AZ         3  2.477837e+06
OH         1  2.423390e+06
UT         5  2.017415e+06
WA         3  1.591927e+06
HI         2  1.575569e+06
AR         1  1.544300e+06

In [ ]:
# Grouping by two keys


# this creates a two-level index (multiindex)

NameError: name 'ppopositive' is not defined

In [12]:
two_key = national_parks.positive


two_key['IM', 'WY']

AttributeError: 'DataFrame' object has no attribute 'positive'

In [ ]:
# this is the way out of a multiindex
#  result is just a plain DataFrame with three columns


flat = two_key.reset_index()
flat.head()

  region state      visitors
0     AK    AK  1.204881e+05
1     IM    AZ  1.009639e+06
2     IM    CO  6.353273e+05
3     IM    MT  9.908449e+05
4     IM    NM  4.702549e+05